# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  fetch_secrets:
    runs-on: ubuntu-latest
    permissions:  # IMPORTANT - both of these are required
      id-token: write
      contents: read
    name: Fetch some static secrets
    steps:
    - name: Fetch secrets from AKeyless
      id: fetch-secrets
      uses: akeyless-community/akeyless-github-action@v1.0.1
      with:
        api-url: https://api.akeyless.io # ${{ secrets.MY_CM_GATEWAY }} # https://dke.hanzarouth.ca:443/akeyless-api/v2
        access-id: p-uvxbf8zpbpxwom    # (github client: 'p-uvxbf8zpbpxwom', gateway-admin 'p-yc80t8z5oxzj', ex: 'p-iwt13fd19ajd') We recommend storing this as a GitHub Actions secret
        access-type: jwt
        ca-certificate: hanzarouththales/henry/api.akeyless.io.pem # ${{ secrets.NODE_EXTRA_CA_CERTS }} # hanzarouththales/henry/zerosslcacert.pem
        static-secrets: |
          - name: "/henry/gitsecret1"
            output-name: "my_first_secret"
          # static-secrets: '{"/henry/gitsecret2":"my_first_secret"}'
        
    - name: Use Outputs
      run: |
        echo "Step Outputs"
        echo "my_first_secret:${{ steps.fetch-secrets.outputs.my_first_secret }}" >> secret.txt
        cat secret.txt
                
        echo "Environment Variables"
        echo "my_first_secret:${{ env.my_first_secret }}" >> secret.txt
        cat secret.txt
