# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  fetch_secrets:
    runs-on: NUC3 #self-hosted #ubuntu-latest
    permissions:  # IMPORTANT - both of these are required
      id-token: write
      contents: read
    name: Fetch some static secrets
    steps:
    - name: Fetch secrets from AKeyless
      id: fetch-secrets
      uses: akeyless-community/akeyless-github-action@v1.1.2
      with:
        api-url: https://dke.hanzarouth.ca/akeyless-api/v2 # ${{ vars.MY_CM_GATEWAY }} #  or https://api.akeyless.io 
        access-id: p-uvxbf8zpbpxwom    # (github client: 'p-uvxbf8zpbpxwom', gateway-admin 'p-yc80t8z5oxzj', ex: 'p-iwt13fd19ajd') We recommend storing this as a GitHub Actions secret
        access-type: jwt
        # ca-certificate: ${{ vars.NODE_EXTRA_CA_CERTS }} # hanzarouththales/henry/zerosslcacert.pem
        static-secrets: |
          - name: "/henry/gitsecret1"
            output-name: "my_first_secret"
          # static-secrets: '{"/henry/gitsecret2":"my_first_secret"}'
        
    - name: Use Outputs
      run: |
        echo "Step Outputs"
        echo "my_first_secret: ${{ steps.fetch-secrets.outputs.my_first_secret }}" >> secret.txt
        echo "my gateway: ${{ vars.MY_CM_GATEWAY }}" >> secret.txt
        echo "my CA cert: ${{ vars.NODE_EXTRA_CA_CERTS }}" >> secret.txt
                
        echo "Environment Variables"
        echo "my_first_secret: ${{ vars.my_first_secret }}" >> secret.txt
        echo "my gateway: ${{ vars.MY_CM_GATEWAY }}" >> secret.txt
        echo "my CA cert: ${{ vars.NODE_EXTRA_CA_CERTS }}" >> secret.txt
        cat secret.txt
